--- 
artifacts: 
  files: 
    - "**/*"
phases: 
  build: 
    commands: 
      - "echo Build started on `date`"
      - "echo Building the Docker image..."
      - "docker build -t usama911/todolist:app ."
      - "docker tag usama911/todolist:app usama911/todolist:app"
  post_build: 
    commands: 
      - "echo Build completed on `date`"
      - "echo Pushing the Docker image..."
      - "docker push usama911/todolist:app"
  pre_build: 
    commands: 
      - "echo Logging in to Docker Hub..."
      - "docker login --username=\"usama911\" --password=\"usama1620\""
version: 0.1
