version: 0.2

phases:
  install:
    commands:
       
      - ls /usr/bin | grep docker

      
  pre_build:
    commands:
      - docker build -t todolist:app .
  build:
    commands:
      - docker images
      - docker run helloworld echo "Hello, World!" 
